# Generated by Django 4.0.5 on 2023-05-06 14:06

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_manager', models.BooleanField(default=False, verbose_name='is_manager')),
                ('is_teknisi', models.BooleanField(default=False, verbose_name='is_teknisi')),
                ('foto', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Gedung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaGedung', models.CharField(max_length=100)),
                ('pengelola', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipeGondola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower', models.CharField(max_length=100)),
                ('tipe', models.CharField(max_length=100)),
                ('gedung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.gedung')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.CharField(max_length=20)),
                ('tgl', models.DateField(blank=True, null=True)),
                ('tipeGondola', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=20)),
                ('catatan', models.CharField(max_length=200)),
                ('fotoKerusakan', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('gedung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.gedung')),
                ('picDua', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pic2', to=settings.AUTH_USER_MODEL)),
                ('picSatu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pic1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl', models.DateField(blank=True, null=True)),
                ('pekerjaan', models.CharField(max_length=200)),
                ('hasilPekerjaan', models.CharField(max_length=100)),
                ('catatanKhusus', models.CharField(max_length=100)),
                ('gedung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.gedung')),
                ('teknisiDua', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pekerja2', to=settings.AUTH_USER_MODEL)),
                ('teknisiSatu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pekerja1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuatBAK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl', models.DateField(blank=True, null=True)),
                ('sparepart', models.CharField(max_length=100)),
                ('spesifikasi', models.CharField(max_length=200)),
                ('qty', models.CharField(max_length=100)),
                ('analisa', models.CharField(max_length=100)),
                ('solusi', models.CharField(max_length=100)),
                ('fotoKerusakan', models.CharField(max_length=100)),
                ('gondola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.tipegondola')),
                ('teknisiDua', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teknisi2', to=settings.AUTH_USER_MODEL)),
                ('teknisiSatu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teknisi1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
