# Generated by Django 4.0.5 on 2023-05-06 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buatbak',
            name='teknisiSatu',
            field=models.ForeignKey(limit_choices_to={'is_teknisi': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teknisi1', to=settings.AUTH_USER_MODEL),
        ),
    ]
