# Generated by Django 4.0.5 on 2023-06-17 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_alter_karyawan_managers_alter_karyawan_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tipeGondola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.tipegondola'),
        ),
    ]
