# Generated by Django 4.0.5 on 2023-06-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_alter_note_fotokerusakan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='catatan',
            field=models.CharField(max_length=1000),
        ),
    ]
