# Generated by Django 4.0.5 on 2023-06-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_alter_note_catatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='bulan',
            field=models.DateField(null=True),
        ),
    ]
