# Generated by Django 4.0.5 on 2023-06-18 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_alter_buatbak_fotokerusakan_alter_buatbak_tgl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuatBAK',
            new_name='BAK',
        ),
    ]
