# Generated by Django 4.0.5 on 2023-06-24 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0016_rename_buatbak_bak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='tgl',
            field=models.DateField(default=datetime.date(2023, 6, 24), null=True),
        ),
    ]
