# Generated by Django 4.0.5 on 2023-06-24 14:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0017_alter_jadwal_tgl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='tgl',
            field=models.DateField(default=datetime.datetime(2023, 6, 24, 14, 1, 47, 981487, tzinfo=utc), null=True),
        ),
    ]
