# Generated by Django 4.0.5 on 2023-06-29 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0019_alter_jadwal_tgl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='tgl',
            field=models.DateField(default=datetime.datetime(2023, 6, 29, 12, 10, 44, 330256, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='is_admin'),
        ),
    ]
