# Generated by Django 4.0.5 on 2023-06-29 12:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0020_alter_jadwal_tgl_alter_karyawan_is_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karyawan',
            old_name='is_manager',
            new_name='is_admin',
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='tgl',
            field=models.DateField(default=datetime.datetime(2023, 6, 29, 12, 15, 5, 957526, tzinfo=utc), null=True),
        ),
    ]
