# Generated by Django 4.0.5 on 2023-07-02 10:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0021_rename_is_manager_karyawan_is_admin_alter_jadwal_tgl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='tgl',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 10, 11, 33, 577651, tzinfo=utc), null=True),
        ),
    ]
