# Generated by Django 4.0.5 on 2023-07-03 12:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0023_alter_jadwal_tgl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='tgl',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 12, 16, 21, 910009, tzinfo=utc), null=True),
        ),
    ]
